# Generated by Django 4.1.7 on 2023-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Thai', 'Thai'), ('American', 'American'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('Indian', 'Indian')], default='Indian', max_length=50),
        ),
    ]
