# Generated by Django 4.1.7 on 2023-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ingredients', models.TextField(null=True)),
                ('category', models.CharField(choices=[('Thai', 'Thai'), ('American', 'American'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('Indian', 'Indian')], default='Indian', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
