# Generated by Django 4.1.7 on 2023-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_instagrampost_delete_category_delete_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('pass_word', models.CharField(max_length=255)),
            ],
        ),
    ]
