# Generated by Django 4.1.7 on 2023-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_instagramlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='user_name',
            field=models.TextField(blank=True),
        ),
    ]
