# Generated by Django 4.1.7 on 2023-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_instagrampost_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
